FROM alpine:3.13

RUN apk add gcc g++ curl bash yarn npm git zip unzip boost make inotify-tools

RUN curl https://cli-assets.heroku.com/install.sh | sh

RUN adduser -D javaUser

USER javaUser

WORKDIR /home/javaUser

RUN curl -s "https://get.sdkman.io" | bash

RUN bash -c "source /home/javaUser/.sdkman/bin/sdkman-init.sh;sdk version;sdk install gradle;sdk install maven"

RUN bash -c " echo The development environment setup is completed."

EXPOSE 4000 3000 3035 9000 3001
