version: '3'
services:

  db:
    image: postgres:9.6.21-alpine
    container_name: pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_dev

  webserver:
    image: nginx:1.18-alpine
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=80

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web_container
    restart: always
    volumes:
      - ./src:/home/javaUser:delegated
    ports:
      - "4000:4000"
      - "3000:3000"
      - "3035:3035"
      - "9000:9000"
      - "3001:3001"
    depends_on:
      - db
      - webserver
